### ISSUE TITLE
Buttons not displayed after "Create folder in DMS"

### ISSUE THREAD

**Issue by cauzitsebastien** [acsone/alfodoo#120]
On odoo 12, I have installed alfodoo-12.0-dev and connector-cmis-12.0.
The confguration of the cmis backend is OK.
I have had a cmis_folder = fields.CmisFolder() in project.project and so, the button "Create folder in DMS" is shown on the project view. When I click on the button, a folder is created in Alfresco.
But no buttons are now showed on the project view in order to add a file or create a directory. And if I had files or directory in the created directory in Alfresco, they are not showed in the project view.

PS : excuse my english, I'm french
PS 2 : my target is to teach how to use odoo and alfresco to students of a school management in Toulouse

**Comment by Zenami1** [comment]
Did you find a solution to this problem?

**Comment by lmignon** [comment]
IMO if you take a look into the browser console, you'll see some errors.. Most probably CORS errors if your alfresco is not properly configured. There are others configuration parameters required into alfresco but those depends of the alfresco version. IE into alfresco 6.2 you must specifically allow basic auth and put some additional parameters to activate the cmis browser binding...
```
alfresco.restApi.basicAuthScheme=true
opencmis.context.override=true
opencmis.context.value=
opencmis.servletpath.override=true
opencmis.servletpath.value=
opencmis.server.override=true
opencmis.server.value=http://my_alfresco:8080/alfresco/api/
```

**Comment by Zenami1** [comment]
These are the errors I get:

`Error:
Uncaught TypeError: Cannot read property 'constructor' of undefined

http://localhost:8069/web/content/511-bdab48b/web.assets_backend.js:406
Traceback:
TypeError: Cannot read property 'constructor' of undefined
    at wrap_context (http://localhost:8069/web/content/511-bdab48b/web.assets_backend.js:406:8)
    at http://localhost:8069/web/content/511-bdab48b/web.assets_backend.js:413:156
    at Function._.each._.forEach (http://localhost:8069/web/content/317-ea04ea4/web.assets_common.js:12:558)
    at _.<computed> [as each] (http://localhost:8069/web/content/317-ea04ea4/web.assets_common.js:69:526)
    at eval_domains (http://localhost:8069/web/content/511-bdab48b/web.assets_backend.js:412:265)
    at Object.pyeval [as eval] (http://localhost:8069/web/content/511-bdab48b/web.assets_backend.js:428:24)
    at OdooClass.stringToArray (http://localhost:8069/web/content/511-bdab48b/web.assets_backend.js:383:2283)
    at Class._getDomain (http://localhost:8069/web/content/511-bdab48b/web.assets_backend.js:1446:98)
    at Class._fetchSpecialMany2ones (http://localhost:8069/web/content/511-bdab48b/web.assets_backend.js:1415:72)
    at Class._fetchSpecialStatus (http://localhost:8069/web/content/511-bdab48b/web.assets_backend.js:1420:176)`
