### ISSUE TITLE
[10.0-cmis_report_write-jne] --TypeError: get_pdf() takes at least 5 arguments (4 given)

### ISSUE THREAD

**Issue by LakshminarayananOKN** [acsone/alfodoo#40]
alfodoo-10.0-cmis_report_write-jne - installed and configured, cmis field implemented in sale order, while printing sale order getting error like this

Traceback (most recent call last):
  File "/home/iswasu-4/Desktop/odoo-10.0-e-20161123/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/home/iswasu-4/Desktop/odoo-10.0-e-20161123/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/iswasu-4/Desktop/odoo-10.0-e-20161123/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
TypeError: get_pdf() takes at least 5 arguments (4 given)

**Comment by lmignon** [comment]
@LakshminarayananOKN This addon is experimental and requires a patch on Odoo. Nevertheless, the problem described should be resolved.
