### ISSUE TITLE
Alfodoo not picking backend_name 

### ISSUE THREAD

**Issue by ydaniels** [acsone/alfodoo#59]
Creating a module this way
```

class AccountIn(models.Model):
    _inherit = 'account.invoice'

    my_folder = fields.CmisFolder(backend_name="account", string="Account CMIS")
```

```

def get_backend(self, env, raise_if_not_found=True):
        return env['cmis.backend'].get_by_name(
            self.backend_name, raise_if_not_found)
```
self.backend_name is always None line 94 file cmis_folder.py

**Comment by lmignon** [comment]
@ydaniels Are you sure? This use case is covered by the testsuite. On which version? Into an odoo shell can you check what's the result of 
```python
self.env['account.invoice']._fields['cmis_folder'].backend_name
```

**Comment by ydaniels** [comment]
output from testing
```
2017-06-27 19:15:39,347 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: ERROR: test_get_by_name (odoo.addons.cmis_field.tests.test_cmis_backend.TestCmisBackend)
2017-06-27 19:15:39,348 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: Traceback (most recent call last):
2017-06-27 19:15:39,348 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `   File "/opt/odoo/custom/erpsoftapp10/cmis_field/tests/test_cmis_backend.py", line 15, in setUp
2017-06-27 19:15:39,348 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `     self.backend_instance = self.env.ref('cmis.cmis_backend_alfresco')
2017-06-27 19:15:39,348 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `   File "/opt/odoo/odoo/odoo/api.py", line 785, in ref
2017-06-27 19:15:39,349 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `     return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
2017-06-27 19:15:39,349 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `   File "/opt/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1055, in xmlid_to_object
2017-06-27 19:15:39,349 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `     t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
2017-06-27 19:15:39,349 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `   File "/opt/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1039, in xmlid_to_res_model_res_id
2017-06-27 19:15:39,349 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `     return self.xmlid_lookup(xmlid)[1:3]
2017-06-27 19:15:39,350 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `   File "<decorator-gen-28>", line 2, in xmlid_lookup
2017-06-27 19:15:39,350 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `   File "/opt/odoo/odoo/odoo/tools/cache.py", line 87, in lookup
2017-06-27 19:15:39,350 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `     value = d[key] = self.method(*args, **kwargs)
2017-06-27 19:15:39,350 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `   File "/opt/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1028, in xmlid_lookup
2017-06-27 19:15:39,350 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: `     raise ValueError('External ID not found in the system: %s' % xmlid)
2017-06-27 19:15:39,351 22269 ERROR alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: ` ValueError: External ID not found in the system: cmis.cmis_backend_alfresco
2017-06-27 19:15:39,351 22269 INFO alfodoo odoo.addons.cmis_field.tests.test_cmis_backend: ======================================================================
```
This error occurs during installation so i cant i test in shell
![selection_001](https://user-images.githubusercontent.com/8302768/27610081-fc0ae68c-5b5a-11e7-9c4d-691743280c91.png)

**Comment by lmignon** [comment]
@ydaniels Thank you for theses additional informations. The error at server start occurs when you have more than 1 backend configured AND cmis_folder fields configured without a` backend_name`. As of you have more than one backend, the `backend_name` is required on each field.

The error when you run the tests seems to indicate that the tests are not run on en empty databases with the demo data.

Which Odoo version do you use?

**Comment by ydaniels** [comment]
Yes cmis_folder is configured with a backend_name

```
class ProjectPro(models.Model):
    _inherit = 'project.project'

    cmis_folder = fields.CmisFolder(backend_name="project", string="Project CMIS")
```
odoo version 10.0 final
As i have said above the variable changes to None somewhere in the  class
```
def get_backend(self, env, raise_if_not_found=True):
        return env['cmis.backend'].get_by_name(
            self.backend_name, raise_if_not_found)
```
the self.backend_name is None in this method. If the bug is not from alfodoo then it should be from odoo

**Comment by lmignon** [comment]
@ydaniels OK, I've to setup a proper environment to try to reproduce the problem. Unfortunately I'm very busy for the moment....

**Comment by ydaniels** [comment]
ok

**Comment by pschweitz** [comment]
Hi,
I have the same issue. I use Odoo 10, the version of the 25th of April (commit: d5384f8)

It looks like Odoo loads the field several times, but some without the backend name, then when opening the view, it binds with one not having corresponding backend name, but "None" instead.

I printed some traces at loading. We can see 2 fields I created with a backend name, I do not have created the others:

```
2017-07-09 10:47:05,118 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: START: CmisFolder.__init__()
2017-07-09 10:47:05,118 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: backend_name: Alfresco1
2017-07-09 10:47:05,118 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: string: None
2017-07-09 10:47:05,119 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: kwargs: {}
2017-07-09 10:47:05,120 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: START: CmisFolder.__init__()
2017-07-09 10:47:05,120 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: backend_name: Alfresco2
2017-07-09 10:47:05,121 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: string: None
2017-07-09 10:47:05,121 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: kwargs: {}
2017-07-09 10:47:05,229 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: START: CmisFolder.__init__()
2017-07-09 10:47:05,230 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: backend_name: None
2017-07-09 10:47:05,230 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: string: None
2017-07-09 10:47:05,230 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: kwargs: {}
2017-07-09 10:47:05,278 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: START: CmisFolder.__init__()
2017-07-09 10:47:05,278 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: backend_name: None
2017-07-09 10:47:05,278 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: string: None
2017-07-09 10:47:05,278 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: kwargs: {}
2017-07-09 10:47:05,299 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: START: CmisFolder.__init__()
2017-07-09 10:47:05,300 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: backend_name: None
2017-07-09 10:47:05,300 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: string: None
2017-07-09 10:47:05,301 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: kwargs: {'inherited': True, 'copy': True, 'related': ('partner_id', 'cmis_folder_partner2'), 'related_sudo': False}
```

Then when loading the view:

```
2017-07-09 10:47:05,661 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: START: CmisFolder.get_backend()
2017-07-09 10:47:05,664 4550 DEBUG demo odoo.addons.cmis_field.fields.cmis_folder: self.backend_name: None
```

Could you confirm it can come from the Odoo's engine ?
Or could it be something wrong in my configuration, and/or is there any workaround ?

Thanks for your contribution

Philippe

**Comment by ydaniels** [comment]
Hello have you confirmed the bug. seems @pschweitz has the same issues.

**Comment by lmignon** [comment]
@ydaniels I've to work on it but I'm still busy with a lot of others priorities since my clients are not impacted by this bug...

**Comment by lmignon** [comment]
@ydaniels @pschweitz A suggestion: can you check if the bug is present if the server is started with '--load=web,kanban,cmis_field'

**Comment by lmignon** [comment]
@ydaniels Do you have fixed the problem?

**Comment by ydaniels** [comment]
No not really, but i have not tested with the latest alfodoo version

**Comment by phuhk** [comment]
hi @lmignon, this exactly same my the problem. Any idea around this, mate?

**Comment by lmignon** [comment]
@phuhk Sorry but I'm not able to reproduce the problem. (at least in my unitests)
How do you have defined the field? Within a custom module or using the UI?
