### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by max3903** [acsone/alfodoo#62]
Hello,

I am using Odoo 10.0 and Alfresco Community 5.2.0:

Alfresco Share v5.2.e
(r135148-b16, Aikau 1.0.101.3, Spring Surf 5.2.e, Spring WebScripts 6.13, Freemarker 2.3.20-alfresco-patched, Rhino 1.7R4-alfresco-patched, Yui 2.9.0-alfresco-20141223)
Alfresco Community v5.2.0
(r135134-b14) schema 10005

I created and installed a module to add a Documents tab on res.partner.

When I click on the Documents tab or edit the res.partner, I get the following error message:

```
https://********************/web/content/1122-305078b/web.assets_backend.js:5338
Traceback:
TypeError: Cannot read property 'type' of undefined
    at Class.on_cmis_error (https://********************/web/content/1122-305078b/web.assets_backend.js:5338:84)
    at https://********************/web/content/1122-305078b/web.assets_backend.js:5337:642
    at https://********************/web/content/1122-305078b/web.assets_backend.js:3267:1933
    at Request.callback (https://********************/web/content/1122-305078b/web.assets_backend.js:3196:163)
    at Request.crossDomainError (https://********************/web/content/1122-305078b/web.assets_backend.js:3196:490)
    at XMLHttpRequest.xhr.onreadystatechange (https://********************/web/content/1122-305078b/web.assets_backend.js:3197:94)
```

Any idea?

**Comment by lmignon** [comment]
@max3903 This kind of error occurs when the alfresco CORS configuration is not right. In such a case you should find into the browser error logs a more explicit message complaining about an not allowed access to cross-origin resource.

**Comment by max3903** [comment]
@lmignon CORS configuration is fixed now. Thanks.

**Comment by Zenami1** [comment]
What should be the configuration of CORS? I'm getting the same error
