### ISSUE TITLE
Value error:invalid literal

### ISSUE THREAD

**Issue by sumankhk** [acsone/alfodoo#93]
Traceback (most recent call last):
  File "/home/odoomaster/odoo-dev/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoomaster/odoo-dev/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoomaster/odoo-dev/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoomaster/odoo-dev/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoomaster/odoo-dev/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoomaster/odoo-dev/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoomaster/odoo-dev/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoomaster/odoo-dev/pta_ltd/cmis_field/controllers/main.py", line 13, in create_field_value
    model_inst._fields[field_name].create_value(model_inst)
  File "/home/odoomaster/odoo-dev/pta_ltd/cmis_field/fields/cmis_folder.py", line 110, in create_value
    self._create_in_cmis(records, backend)
  File "/home/odoomaster/odoo-dev/pta_ltd/cmis_field/fields/cmis_folder.py", line 114, in _create_in_cmis
    parents = self.get_create_parents(records, backend)
  File "/home/odoomaster/odoo-dev/pta_ltd/cmis_field/fields/cmis_folder.py", line 169, in get_create_parents
    path_parts, create_if_not_found=True)
  File "/home/odoomaster/odoo-dev/pta_ltd/cmis_field/models/cmis_backend.py", line 122, in get_folder_by_path_parts
    path, create_if_not_found, cmis_parent_objectid)
  File "/home/odoomaster/odoo-dev/pta_ltd/cmis/models/cmis_backend.py", line 98, in get_folder_by_path
    repo = self.get_cmis_repository()
  File "/home/odoomaster/odoo-dev/pta_ltd/cmis/models/cmis_backend.py", line 58, in get_cmis_repository
    return client.defaultRepository
  File "/usr/local/lib/python2.7/dist-packages/cmislib/model.py", line 102, in getDefaultRepository
    return self.binding.getRepositoryService().getDefaultRepository(self)
  File "/usr/local/lib/python2.7/dist-packages/cmislib/browser/binding.py", line 154, in getDefaultRepository
    result = client.binding.get(client.repositoryUrl, client.username, client.password, **client.extArgs)
  File "/usr/local/lib/python2.7/dist-packages/cmislib/browser/binding.py", line 76, in get
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cmislib/net.py", line 67, in get
    return h.request(url, method='GET', headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1511, in request
    proxy_info = self._get_proxy_info(scheme, authority)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1696, in _get_proxy_info
    proxy_info = proxy_info(scheme)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 844, in proxy_info_from_environment
    pi = proxy_info_from_url(url, method)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 879, in proxy_info_from_url
    port = int(port)
ValueError: invalid literal for int() with base 10: ':1%eth0]:13128'

Please help...why is this error occuring and how do i resolve it?
@zakiuu @lmignon

**Comment by sumankhk** [comment]
it is urgent guys..can anybody help?
@lmignon @sbidoul

**Comment by sumankhk** [comment]
its been 3 days already ...and i've not got any help? i would really appreciate if anybody could help...
@lmignon @sbidoul @zakiuu @Cedric-Pigeon @max3903

**Comment by sumankhk** [comment]
@lmignon

**Comment by lmignon** [comment]
@sumankhk Which version of Alfresco do you use? In some cases, a bug in alfresco prevents the generation of a RFC compliant 'www-authenticate' header (https://issues.alfresco.com/jira/browse/MNT-15819)
In such a case, a workaround is to patch httplib2 BEFORE the first import of the lib with the followingg code:

```python
import wrapt
@wrapt.patch_function_wrapper('httplib2', '_parse_www_authenticate')
def wrapper(wrapped, instance, args, kwargs):
    headers = kwargs.get('headers') or args[0]
    headername = kwargs.get('headername') or  args[1]
    if headername == 'www-authenticate' and headers.has_key(headername):
        authenticate = headers[headername].strip()
        if len(authenticate.split(" ")) < 2:
            # A BUG into alfresco generates non RFC compliant
            # 'www-authenticate' header
            # https://issues.alfresco.com/jira/browse/MNT-15819
            # work around this bug and but force Basic auth into the supported
            # authentication
            authenticate = authenticate + ' , Basic realm=""'
            headers[headername] = authenticate
            return wrapped(headers, headername)
    return wrapped(*args, **kwargs)

```
For one of our client, I've put this code as first lines of in cmislib/__init__py 

This relies on the 'wrapt' python package.

see https://github.com/acsone/chemistry-cmislib/commit/2fe8d3f65a6e5c714ade1f427ac6ece645848823

**Comment by lmignon** [comment]
@sumankhk  I close this issue. Feel free to reopen-it if it's not fixed.
